-- 公式スポットのタグ整備と、同じ場所の重複登録の削除（2026-09-26）
-- Supabase ダッシュボードの SQL Editor で1回実行する。
-- 何度実行しても結果が変わらないよう、追加は on conflict do nothing、削除・移動は対象が無ければ何もしない書き方にしてある。
-- 対象は公式アカウント(profiles.username = 'LIMap')のスポットのみ。
--
-- 内容:
--   1. 新しいタグ 90 個を作る
--   2. 誤字タグ（世界遗産→世界遺産、産業遗産→産業遺産）を付け替えて、誤字タグを削除する
--   3. 同じ場所の重複登録 13 か所について、削除するスポットの SNS 埋め込みを残すスポットへ移す（同じURLは1つにまとめる）
--   4. 重複登録 27 件を削除する（写真・レビュー・いいね・行きたい は付いていないことを確認済み）
--   5. 公式スポットにタグを付ける（1126 組。既に付いているものはそのまま）
--   6. どのスポットにも使われていない誤字タグ（廃墨、青専ビル街）を削除する
--
-- 削除したスポットのURLは、vercel.json のリダイレクトで残すスポットへ転送する（別途 push）。

begin;

-- 1. 新しいタグ
insert into public.tags (name) values
  ('アゼルバイジャン'),
  ('アメリカ'),
  ('アラブ首長国連邦'),
  ('アルゼンチン'),
  ('アンゴラ'),
  ('イギリス'),
  ('イタリア'),
  ('インド'),
  ('ウクライナ'),
  ('ウズベキスタン'),
  ('エジプト'),
  ('オランダ'),
  ('オーストラリア'),
  ('オーストリア'),
  ('カザフスタン'),
  ('カナダ'),
  ('コートジボワール'),
  ('スイス'),
  ('スウェーデン'),
  ('スペイン'),
  ('スリランカ'),
  ('セルビア'),
  ('タイ'),
  ('チェコ'),
  ('チリ'),
  ('トルクメニスタン'),
  ('トルコ'),
  ('ドイツ'),
  ('ナミビア'),
  ('ノルウェー'),
  ('フランス'),
  ('ブラジル'),
  ('ブルガリア'),
  ('ブルータリズム'),
  ('ベトナム'),
  ('ベルギー'),
  ('ボスニア・ヘルツェゴビナ'),
  ('ポルトガル'),
  ('マレーシア'),
  ('メキシコ'),
  ('ルーマニア'),
  ('ロシア'),
  ('三重'),
  ('世界遺産'),
  ('中国'),
  ('佐賀'),
  ('北マケドニア'),
  ('北朝鮮'),
  ('北海道'),
  ('千葉'),
  ('南アフリカ'),
  ('台湾'),
  ('商店街'),
  ('埼玉'),
  ('大分'),
  ('大阪'),
  ('奈良'),
  ('宮城'),
  ('宮崎'),
  ('山口'),
  ('山形'),
  ('山梨'),
  ('岐阜'),
  ('岡山'),
  ('岩手'),
  ('広島'),
  ('愛媛'),
  ('愛知'),
  ('新潟'),
  ('映画館・劇場'),
  ('水没'),
  ('滋賀'),
  ('炭鉱'),
  ('熊本'),
  ('神奈川'),
  ('福井'),
  ('福岡'),
  ('福島'),
  ('秋田'),
  ('群馬'),
  ('茨城'),
  ('鉱山'),
  ('長崎'),
  ('長野'),
  ('青森'),
  ('静岡'),
  ('韓国'),
  ('香港'),
  ('高知'),
  ('鳥取')
on conflict (name) do nothing;

-- 2. 誤字タグの付け替え
insert into public.tags (name) values ('世界遺産') on conflict (name) do nothing;
insert into public.spot_tags (spot_id, tag_id)
select st.spot_id, (select id from public.tags where name = '世界遺産')
from public.spot_tags st join public.tags t on t.id = st.tag_id
where t.name = '世界遗産'
on conflict do nothing;
delete from public.tags where name = '世界遗産';
insert into public.tags (name) values ('産業遺産') on conflict (name) do nothing;
insert into public.spot_tags (spot_id, tag_id)
select st.spot_id, (select id from public.tags where name = '産業遺産')
from public.spot_tags st join public.tags t on t.id = st.tag_id
where t.name = '産業遗産'
on conflict do nothing;
delete from public.tags where name = '産業遗産';

-- 3. 重複登録の SNS 埋め込みを、残すスポットへ移す（残す側に同じURLがあれば移さない）
-- スパリゾートハワイアンズ スプリングパーク: 残す HLy7yJkZ / 削除 gVpMv3sF
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'HLy7yJkZ' and d.slug = 'gVpMv3sF' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 旧摩耶観光ホテル: 残す MgcgYpSc / 削除 Durek4me
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'MgcgYpSc' and d.slug = 'Durek4me' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- タウシュベツ川橋梁: 残す BQQBELWM / 削除 8P62RQ4b 7JEYfcMq CE5ifrEg qwhvjG2A
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'BQQBELWM' and d.slug = '8P62RQ4b' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'BQQBELWM' and d.slug = '7JEYfcMq' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'BQQBELWM' and d.slug = 'CE5ifrEg' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'BQQBELWM' and d.slug = 'qwhvjG2A' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 松尾鉱山アパート跡: 残す YfVjS3B4 / 削除 7EroKRG5 uHZ4fzpk rr8kyvmW KroztUgb Z9gmUCX8
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'YfVjS3B4' and d.slug = '7EroKRG5' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'YfVjS3B4' and d.slug = 'uHZ4fzpk' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'YfVjS3B4' and d.slug = 'rr8kyvmW' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'YfVjS3B4' and d.slug = 'KroztUgb' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'YfVjS3B4' and d.slug = 'Z9gmUCX8' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 神子畑選鉱場跡: 残す tZU5uY9m / 削除 TcFVwTPr KP6yRJ57 gtR5PyQE
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'tZU5uY9m' and d.slug = 'TcFVwTPr' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'tZU5uY9m' and d.slug = 'KP6yRJ57' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'tZU5uY9m' and d.slug = 'gtR5PyQE' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 別子銅山 東平地区: 残す C3r5rXkW / 削除 ntDNVgAx ZF6Qaa7Z
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'C3r5rXkW' and d.slug = 'ntDNVgAx' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'C3r5rXkW' and d.slug = 'ZF6Qaa7Z' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 旧志免鉱業所竪坑櫓: 残す ffbCQ6bM / 削除 dYEKAPeM x4vnpidR grw5PEER 6mrjy8Sd
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'ffbCQ6bM' and d.slug = 'dYEKAPeM' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'ffbCQ6bM' and d.slug = 'x4vnpidR' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'ffbCQ6bM' and d.slug = 'grw5PEER' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'ffbCQ6bM' and d.slug = '6mrjy8Sd' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 化女沼レジャーランド跡: 残す DpsXBFr5 / 削除 KXzAaiXG
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'DpsXBFr5' and d.slug = 'KXzAaiXG' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 定山渓観光ホテル 山渓苑: 残す 4y7VrgGL / 削除 nVN9vpGa TPYMPaY5
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = '4y7VrgGL' and d.slug = 'nVN9vpGa' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = '4y7VrgGL' and d.slug = 'TPYMPaY5' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 旧犬鳴トンネル: 残す vZntGVz6 / 削除 mEJND5DN
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'vZntGVz6' and d.slug = 'mEJND5DN' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 旧国鉄士幌線 幌加駅跡: 残す AjQzCCkp / 削除 6MfifXWm
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'AjQzCCkp' and d.slug = '6MfifXWm' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 旧中西薬局: 残す eKpNs9Zn / 削除 FK5tQAEr
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'eKpNs9Zn' and d.slug = 'FK5tQAEr' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);
-- 我路円形校舎（沼東小学校）: 残す gu6VsXgq / 削除 q2NJ38Xb
update public.spot_embeds e
set spot_id = k.id,
    position = (select coalesce(max(position), -1) + 1 from public.spot_embeds where spot_id = k.id)
from public.spots k, public.spots d
where k.slug = 'gu6VsXgq' and d.slug = 'q2NJ38Xb' and e.spot_id = d.id
  and not exists (select 1 from public.spot_embeds x where x.spot_id = k.id and x.url = e.url);

-- 4. 重複登録の削除（spot_tags・spot_embeds などは on delete cascade で一緒に消える）
delete from public.spots
where slug in (
  'gVpMv3sF',
  'Durek4me',
  '8P62RQ4b',
  '7JEYfcMq',
  'CE5ifrEg',
  'qwhvjG2A',
  '7EroKRG5',
  'uHZ4fzpk',
  'rr8kyvmW',
  'KroztUgb',
  'Z9gmUCX8',
  'TcFVwTPr',
  'KP6yRJ57',
  'gtR5PyQE',
  'ntDNVgAx',
  'ZF6Qaa7Z',
  'dYEKAPeM',
  'x4vnpidR',
  'grw5PEER',
  '6mrjy8Sd',
  'KXzAaiXG',
  'nVN9vpGa',
  'TPYMPaY5',
  'mEJND5DN',
  '6MfifXWm',
  'FK5tQAEr',
  'q2NJ38Xb'
)
  and author_id = (select id from public.profiles where username = 'LIMap');

-- 5. タグ付け
insert into public.spot_tags (spot_id, tag_id)
select s.id, t.id
from (values
  ('TdJmev6C', '廃墟'),
  ('TdJmev6C', '栃木'),
  ('TdJmev6C', 'ホテル'),
  ('TdJmev6C', '橋'),
  ('TdJmev6C', '日本'),
  ('TdJmev6C', '温泉'),
  ('7eD74Vfb', 'リミナルスペース'),
  ('7eD74Vfb', '平成レトロ'),
  ('7eD74Vfb', 'ドリームコア'),
  ('7eD74Vfb', '商業施設'),
  ('7eD74Vfb', '広島'),
  ('uAvsFVzp', 'リミナルスペース'),
  ('uAvsFVzp', '平成レトロ'),
  ('uAvsFVzp', '商業施設'),
  ('uAvsFVzp', '青森'),
  ('HLy7yJkZ', 'リミナルスペース'),
  ('HLy7yJkZ', 'ドリームコア'),
  ('HLy7yJkZ', 'プールコア'),
  ('HLy7yJkZ', 'レジャー施設'),
  ('HLy7yJkZ', '福島'),
  ('3ZXPPqYu', 'リミナルスペース'),
  ('3ZXPPqYu', 'プールコア'),
  ('3ZXPPqYu', 'ホテル'),
  ('3ZXPPqYu', '北海道'),
  ('bUpymfK9', 'リミナルスペース'),
  ('bUpymfK9', '昭和レトロ'),
  ('bUpymfK9', '駅'),
  ('bUpymfK9', '無人駅'),
  ('bUpymfK9', '神奈川'),
  ('W9n7DymW', 'リミナルスペース'),
  ('W9n7DymW', '昭和レトロ'),
  ('W9n7DymW', '商業施設'),
  ('W9n7DymW', '東京'),
  ('sTsoVeXe', 'リミナルスペース'),
  ('sTsoVeXe', '昭和レトロ'),
  ('sTsoVeXe', '商業施設'),
  ('sTsoVeXe', '岩手'),
  ('VwXjTi86', 'リミナルスペース'),
  ('VwXjTi86', '高層ビル街'),
  ('VwXjTi86', '地下通路'),
  ('VwXjTi86', '地下'),
  ('VwXjTi86', '東京'),
  ('H4waUzkv', 'リミナルスペース'),
  ('H4waUzkv', '廃墟感'),
  ('H4waUzkv', '商業施設'),
  ('H4waUzkv', '愛知'),
  ('AQ8Q9NVr', 'リミナルスペース'),
  ('AQ8Q9NVr', 'レトロ建築'),
  ('AQ8Q9NVr', '駅'),
  ('AQ8Q9NVr', '福井'),
  ('uN8qRiyB', 'リミナルスペース'),
  ('uN8qRiyB', '秘湯'),
  ('uN8qRiyB', '温泉'),
  ('uN8qRiyB', '大分'),
  ('LjapW5Hz', 'リミナルスペース'),
  ('LjapW5Hz', 'ゲームスポット'),
  ('LjapW5Hz', '駅'),
  ('LjapW5Hz', '地下鉄駅'),
  ('LjapW5Hz', '地下通路'),
  ('LjapW5Hz', '地下'),
  ('LjapW5Hz', '東京'),
  ('fMm9FwDX', 'リミナルスペース'),
  ('fMm9FwDX', '地下通路'),
  ('fMm9FwDX', '地下'),
  ('fMm9FwDX', '東京'),
  ('NbGc4Sdz', 'リミナルスペース'),
  ('NbGc4Sdz', 'ゴーストタウン'),
  ('NbGc4Sdz', '商業施設'),
  ('NbGc4Sdz', '兵庫'),
  ('ZMkEuArd', 'リミナルスペース'),
  ('ZMkEuArd', '世界遺産'),
  ('ZMkEuArd', '炭鉱'),
  ('ZMkEuArd', '産業遺産'),
  ('ZMkEuArd', '廃墟'),
  ('ZMkEuArd', 'ゴーストタウン'),
  ('ZMkEuArd', '長崎'),
  ('tbdAv23o', 'リミナルスペース'),
  ('tbdAv23o', '水没スポット'),
  ('tbdAv23o', '水没'),
  ('tbdAv23o', '廃墟'),
  ('tbdAv23o', '岡山'),
  ('gTe8qwaP', 'リミナルスペース'),
  ('gTe8qwaP', '廃墟'),
  ('gTe8qwaP', '廃ホテル'),
  ('gTe8qwaP', '岡山'),
  ('XBXoFcN3', 'リミナルスペース'),
  ('XBXoFcN3', '廃墟'),
  ('XBXoFcN3', '商業施設'),
  ('XBXoFcN3', '兵庫'),
  ('2xZbLSo5', 'リミナルスペース'),
  ('2xZbLSo5', '廃墟'),
  ('2xZbLSo5', '炭鉱'),
  ('2xZbLSo5', '産業遺産'),
  ('2xZbLSo5', 'ゴーストタウン'),
  ('2xZbLSo5', '長崎'),
  ('ncUNG4h3', 'リミナルスペース'),
  ('ncUNG4h3', '産業遺産'),
  ('ncUNG4h3', '鉱山'),
  ('ncUNG4h3', '廃墟'),
  ('ncUNG4h3', '新潟'),
  ('rAiYXPVt', 'リミナルスペース'),
  ('rAiYXPVt', '廃墟'),
  ('rAiYXPVt', '戦争遺構'),
  ('rAiYXPVt', '広島'),
  ('pZ2q6Ugg', 'リミナルスペース'),
  ('pZ2q6Ugg', '産業遺産'),
  ('pZ2q6Ugg', '鉱山'),
  ('pZ2q6Ugg', '秋田'),
  ('ULU2BB7S', 'リミナルスペース'),
  ('ULU2BB7S', '産業遺産'),
  ('ULU2BB7S', '炭鉱'),
  ('ULU2BB7S', '世界遺産'),
  ('ULU2BB7S', '熊本'),
  ('mUJPSbt5', 'リミナルスペース'),
  ('mUJPSbt5', '地下街'),
  ('mUJPSbt5', '地下'),
  ('mUJPSbt5', '昭和レトロ'),
  ('mUJPSbt5', '東京'),
  ('g3Pub95b', 'リミナルスペース'),
  ('g3Pub95b', '屋上遊園地'),
  ('g3Pub95b', '昭和レトロ'),
  ('g3Pub95b', '東京'),
  ('VjHQSWFR', 'リミナルスペース'),
  ('VjHQSWFR', '廃病院'),
  ('VjHQSWFR', '廃墟'),
  ('VjHQSWFR', '茨城'),
  ('GE9H3gyW', 'リミナルスペース'),
  ('GE9H3gyW', '水没林'),
  ('GE9H3gyW', '水没'),
  ('GE9H3gyW', '山形'),
  ('5QyLHMCy', 'リミナルスペース'),
  ('5QyLHMCy', '廃トンネル'),
  ('5QyLHMCy', 'トンネル'),
  ('5QyLHMCy', '廃墟'),
  ('5QyLHMCy', '京都'),
  ('GL4Ht6wV', '明るい廃墟'),
  ('GL4Ht6wV', 'リミナルスペース'),
  ('GL4Ht6wV', '商業施設'),
  ('GL4Ht6wV', '滋賀'),
  ('Y2ciMqaA', 'リミナルスペース'),
  ('Y2ciMqaA', '無人駅'),
  ('Y2ciMqaA', '駅'),
  ('Y2ciMqaA', '神奈川'),
  ('c6QEVJB6', 'リミナルスペース'),
  ('c6QEVJB6', '給水塔'),
  ('c6QEVJB6', '団地'),
  ('c6QEVJB6', '東京'),
  ('gE3dSWYN', 'リミナルスペース'),
  ('gE3dSWYN', '廃線跡'),
  ('gE3dSWYN', '廃線'),
  ('gE3dSWYN', '鳥取'),
  ('gf7SinSV', 'リミナルスペース'),
  ('gf7SinSV', '廃駅'),
  ('gf7SinSV', '廃線'),
  ('gf7SinSV', '茨城'),
  ('osSBC4sM', 'リミナルスペース'),
  ('osSBC4sM', '廃ラブホテル'),
  ('osSBC4sM', '廃ホテル'),
  ('osSBC4sM', '廃墟'),
  ('osSBC4sM', '三重'),
  ('7gRLUSMJ', 'リミナルスペース'),
  ('7gRLUSMJ', '廃線橋梁'),
  ('7gRLUSMJ', '橋'),
  ('7gRLUSMJ', '廃線'),
  ('7gRLUSMJ', '宮崎'),
  ('DpsXBFr5', 'リミナルスペース'),
  ('DpsXBFr5', '廃遊園地'),
  ('DpsXBFr5', '廃墟'),
  ('DpsXBFr5', '宮城'),
  ('es2eLiRx', 'リミナルスペース'),
  ('es2eLiRx', '防空壕'),
  ('es2eLiRx', '戦争遺構'),
  ('es2eLiRx', '地下'),
  ('es2eLiRx', '奈良'),
  ('NP7tVnY3', 'リミナルスペース'),
  ('NP7tVnY3', '異世界レジャー'),
  ('NP7tVnY3', 'レジャー施設'),
  ('NP7tVnY3', '三重'),
  ('kusiVgvC', 'リミナルスペース'),
  ('kusiVgvC', '廃ロープウェイ'),
  ('kusiVgvC', '廃墟'),
  ('kusiVgvC', '大分'),
  ('4MzTz3PL', 'リミナルスペース'),
  ('4MzTz3PL', '旧隧道'),
  ('4MzTz3PL', 'トンネル'),
  ('4MzTz3PL', '福井'),
  ('4MzTz3PL', '滋賀'),
  ('o5t5vXLu', 'リミナルスペース'),
  ('o5t5vXLu', '水没村'),
  ('o5t5vXLu', '水没'),
  ('o5t5vXLu', '岐阜'),
  ('bRVna6ES', 'リミナルスペース'),
  ('bRVna6ES', '屋上遊園地'),
  ('bRVna6ES', '昭和レトロ'),
  ('bRVna6ES', '大阪'),
  ('MgcgYpSc', 'リミナルスペース'),
  ('MgcgYpSc', '廃墟'),
  ('MgcgYpSc', '廃ホテル'),
  ('MgcgYpSc', '兵庫'),
  ('FGg4w6Jh', 'リミナルスペース'),
  ('FGg4w6Jh', '地下通路'),
  ('FGg4w6Jh', '駅'),
  ('FGg4w6Jh', '地下'),
  ('FGg4w6Jh', '千葉'),
  ('nPuRMQQp', 'リミナルスペース'),
  ('nPuRMQQp', '無人自販機'),
  ('nPuRMQQp', '廃墟'),
  ('nPuRMQQp', '群馬'),
  ('V6z9Xx58', 'リミナルスペース'),
  ('V6z9Xx58', '団地商店街'),
  ('V6z9Xx58', '団地'),
  ('V6z9Xx58', '商店街'),
  ('V6z9Xx58', '昭和レトロ'),
  ('V6z9Xx58', '東京'),
  ('77BLLqk2', 'リミナルスペース'),
  ('77BLLqk2', 'カプセルホテル'),
  ('77BLLqk2', 'ホテル'),
  ('77BLLqk2', '大阪'),
  ('Rn4ZaCs9', 'リミナルスペース'),
  ('Rn4ZaCs9', 'スターハウス'),
  ('Rn4ZaCs9', '団地'),
  ('Rn4ZaCs9', '集合住宅'),
  ('Rn4ZaCs9', '千葉'),
  ('kk5yFE6g', 'リミナルスペース'),
  ('kk5yFE6g', '廃線鉄橋'),
  ('kk5yFE6g', '橋'),
  ('kk5yFE6g', '廃線'),
  ('kk5yFE6g', '兵庫'),
  ('DmNxYTtA', 'リミナルスペース'),
  ('DmNxYTtA', 'ゴーストタウン'),
  ('DmNxYTtA', '炭鉱'),
  ('DmNxYTtA', '商店街'),
  ('DmNxYTtA', '廃墟'),
  ('DmNxYTtA', '北海道'),
  ('HmgSvMMV', 'リミナルスペース'),
  ('HmgSvMMV', '水没建造物'),
  ('HmgSvMMV', '水没'),
  ('HmgSvMMV', '廃墟'),
  ('HmgSvMMV', '高知'),
  ('YktDGVfG', '廃ホテル'),
  ('YktDGVfG', '廃墟'),
  ('YktDGVfG', '温泉'),
  ('YktDGVfG', '熊本'),
  ('Ff8i4vwk', '屋上遊園地'),
  ('Ff8i4vwk', '愛媛'),
  ('CciNUdTX', '昭和レトロ'),
  ('CciNUdTX', '神奈川'),
  ('LgnWY4Hx', '廃ホテル'),
  ('LgnWY4Hx', '廃墟'),
  ('LgnWY4Hx', '京都'),
  ('vbUQ9kcZ', '地下通路'),
  ('vbUQ9kcZ', '地下'),
  ('vbUQ9kcZ', '駅'),
  ('vbUQ9kcZ', 'ゲームスポット'),
  ('vbUQ9kcZ', '東京'),
  ('KM5aKcco', '地下通路'),
  ('KM5aKcco', '地下'),
  ('KM5aKcco', '駅'),
  ('KM5aKcco', '東京'),
  ('iASM2FaZ', '団地'),
  ('iASM2FaZ', 'ゴーストタウン'),
  ('iASM2FaZ', '廃墟'),
  ('iASM2FaZ', '茨城'),
  ('QxTyYMA9', '廃遊園地'),
  ('QxTyYMA9', '廃墟'),
  ('QxTyYMA9', '栃木'),
  ('Ru5BLnja', '廃病院'),
  ('Ru5BLnja', '廃墟'),
  ('Ru5BLnja', '栃木'),
  ('4y7VrgGL', '廃ホテル'),
  ('4y7VrgGL', '廃墟'),
  ('4y7VrgGL', '温泉'),
  ('4y7VrgGL', '北海道'),
  ('tZU5uY9m', 'リミナルスペース'),
  ('tZU5uY9m', '産業遺産'),
  ('tZU5uY9m', '鉱山'),
  ('tZU5uY9m', '廃墟'),
  ('tZU5uY9m', '兵庫'),
  ('TcnQTVk5', '廃線'),
  ('TcnQTVk5', '廃墟'),
  ('TcnQTVk5', '群馬'),
  ('BQQBELWM', 'リミナルスペース'),
  ('BQQBELWM', '幻の橋'),
  ('BQQBELWM', '橋'),
  ('BQQBELWM', '廃線'),
  ('BQQBELWM', '水没'),
  ('BQQBELWM', '北海道'),
  ('ffbCQ6bM', 'リミナルスペース'),
  ('ffbCQ6bM', '産業遺産'),
  ('ffbCQ6bM', '炭鉱'),
  ('ffbCQ6bM', '福岡'),
  ('Ngoqp3Rw', '産業遺産'),
  ('Ngoqp3Rw', '廃墟'),
  ('Ngoqp3Rw', '岡山'),
  ('JsXsWk9W', '地下'),
  ('JsXsWk9W', '公共施設'),
  ('JsXsWk9W', '埼玉'),
  ('9Gg5tgdq', '廃ホテル'),
  ('9Gg5tgdq', '廃墟'),
  ('9Gg5tgdq', '温泉'),
  ('9Gg5tgdq', '静岡'),
  ('RuCpHWym', 'スキー場跡'),
  ('RuCpHWym', '廃墟'),
  ('RuCpHWym', '福島'),
  ('m52bzS9d', '廃墟'),
  ('m52bzS9d', '三重'),
  ('XEZUwT7C', '廃ホテル'),
  ('XEZUwT7C', '廃墟'),
  ('XEZUwT7C', '温泉'),
  ('XEZUwT7C', '北海道'),
  ('gHBKZTqy', '廃墟'),
  ('gHBKZTqy', '東京'),
  ('G5VgyPMb', '鉱山'),
  ('G5VgyPMb', '産業遺産'),
  ('G5VgyPMb', '廃墟'),
  ('G5VgyPMb', '秋田'),
  ('vHoKaWez', 'トンネル'),
  ('vHoKaWez', '北海道'),
  ('qgSBZ4HG', '鉱山'),
  ('qgSBZ4HG', '産業遺産'),
  ('qgSBZ4HG', '廃墟'),
  ('qgSBZ4HG', '栃木'),
  ('zphbsPDi', '戦争遺構'),
  ('zphbsPDi', '地下'),
  ('zphbsPDi', '長野'),
  ('vZntGVz6', 'トンネル'),
  ('vZntGVz6', '廃墟'),
  ('vZntGVz6', '福岡'),
  ('ybWwuMCE', '戦争遺構'),
  ('ybWwuMCE', '廃発電所'),
  ('ybWwuMCE', '廃墟'),
  ('ybWwuMCE', '広島'),
  ('2tz9ibsF', '廃ホテル'),
  ('2tz9ibsF', '廃墟'),
  ('2tz9ibsF', '温泉'),
  ('2tz9ibsF', '北海道'),
  ('LXxqQyrL', '廃線'),
  ('LXxqQyrL', '宮崎'),
  ('qqCxVs6h', 'トンネル'),
  ('qqCxVs6h', '廃線'),
  ('qqCxVs6h', '山口'),
  ('YfVjS3B4', 'リミナルスペース'),
  ('YfVjS3B4', '廃墟'),
  ('YfVjS3B4', '鉱山'),
  ('YfVjS3B4', '集合住宅'),
  ('YfVjS3B4', 'ゴーストタウン'),
  ('YfVjS3B4', '岩手'),
  ('ZKgQrh3z', '炭鉱'),
  ('ZKgQrh3z', '産業遺産'),
  ('ZKgQrh3z', '廃墟'),
  ('ZKgQrh3z', '長崎'),
  ('C3r5rXkW', 'リミナルスペース'),
  ('C3r5rXkW', '産業遺産'),
  ('C3r5rXkW', '鉱山'),
  ('C3r5rXkW', '廃墟'),
  ('C3r5rXkW', '愛媛'),
  ('NypNZ4hq', '廃校'),
  ('NypNZ4hq', '滋賀'),
  ('fJuqsLen', '廃遊園地'),
  ('fJuqsLen', '廃墟'),
  ('fJuqsLen', '新潟'),
  ('WtRcaRos', '廃ホテル'),
  ('WtRcaRos', '廃墟'),
  ('WtRcaRos', '神奈川'),
  ('AjQzCCkp', '廃線'),
  ('AjQzCCkp', '北海道'),
  ('6JfrFZ2y', '商業施設'),
  ('6JfrFZ2y', '秋田'),
  ('uhtHKNAA', '団地'),
  ('uhtHKNAA', '廃墟'),
  ('uhtHKNAA', '埼玉'),
  ('kLSQhNsf', '炭鉱'),
  ('kLSQhNsf', '集合住宅'),
  ('kLSQhNsf', '廃墟'),
  ('kLSQhNsf', '長崎'),
  ('tbiqnkVs', '鉱山'),
  ('tbiqnkVs', '集合住宅'),
  ('tbiqnkVs', '廃墟'),
  ('tbiqnkVs', '埼玉'),
  ('GXN92tps', '商店街'),
  ('GXN92tps', '昭和レトロ'),
  ('GXN92tps', '宮崎'),
  ('EeKfeyAg', '映画館・劇場'),
  ('EeKfeyAg', '炭鉱'),
  ('EeKfeyAg', '廃墟'),
  ('EeKfeyAg', '北海道'),
  ('eKpNs9Zn', '廃墟'),
  ('eKpNs9Zn', '千葉'),
  ('cEFCuYwU', '廃墟'),
  ('cEFCuYwU', 'レトロ建築'),
  ('cEFCuYwU', '茨城'),
  ('KCC4DazC', '映画館・劇場'),
  ('KCC4DazC', '廃墟'),
  ('KCC4DazC', '栃木'),
  ('MoLLMoNd', '廃ホテル'),
  ('MoLLMoNd', '廃墟'),
  ('MoLLMoNd', '新潟'),
  ('XroRJy6m', '廃発電所'),
  ('XroRJy6m', '廃墟'),
  ('XroRJy6m', '静岡'),
  ('TamekAJY', '廃ホテル'),
  ('TamekAJY', '廃墟'),
  ('TamekAJY', '三重'),
  ('zTqTM2wW', '廃ホテル'),
  ('zTqTM2wW', '廃墟'),
  ('zTqTM2wW', '高知'),
  ('UTtg7ouu', '廃ホテル'),
  ('UTtg7ouu', '廃墟'),
  ('UTtg7ouu', '岡山'),
  ('ZXWghuAD', '廃病院'),
  ('ZXWghuAD', '廃墟'),
  ('ZXWghuAD', '新潟'),
  ('EBE4SgkG', '廃ホテル'),
  ('EBE4SgkG', '廃墟'),
  ('EBE4SgkG', '佐賀'),
  ('wewcfey5', '廃ホテル'),
  ('wewcfey5', '廃墟'),
  ('wewcfey5', '千葉'),
  ('tsMBbRNY', '廃ホテル'),
  ('tsMBbRNY', '廃墟'),
  ('tsMBbRNY', '長野'),
  ('9gxjLGp8', '廃遊園地'),
  ('9gxjLGp8', '廃墟'),
  ('9gxjLGp8', '栃木'),
  ('gu6VsXgq', '廃校'),
  ('gu6VsXgq', '水没'),
  ('gu6VsXgq', '炭鉱'),
  ('gu6VsXgq', '廃墟'),
  ('gu6VsXgq', '北海道'),
  ('9UgkK4kQ', '映画館・劇場'),
  ('9UgkK4kQ', '廃墟'),
  ('9UgkK4kQ', '温泉'),
  ('9UgkK4kQ', '群馬'),
  ('dWApnxeZ', '映画館・劇場'),
  ('dWApnxeZ', '廃墟'),
  ('dWApnxeZ', '福島'),
  ('gTfMpYZv', '廃墟'),
  ('gTfMpYZv', '青森'),
  ('2nZdyNm7', '廃遊園地'),
  ('2nZdyNm7', '廃墟'),
  ('2nZdyNm7', '千葉'),
  ('uaZDcbYY', 'リミナルスペース'),
  ('uaZDcbYY', '廃ホテル'),
  ('uaZDcbYY', '廃墟'),
  ('uaZDcbYY', '静岡'),
  ('yHAia3tA', 'リミナルスペース'),
  ('yHAia3tA', '廃ホテル'),
  ('yHAia3tA', '廃墟'),
  ('yHAia3tA', '温泉'),
  ('yHAia3tA', '栃木'),
  ('RAi2rKjn', 'リミナルスペース'),
  ('RAi2rKjn', '廃ホテル'),
  ('RAi2rKjn', '廃墟'),
  ('RAi2rKjn', '埼玉'),
  ('rKT2maBC', 'リミナルスペース'),
  ('rKT2maBC', '廃校'),
  ('rKT2maBC', '廃墟'),
  ('rKT2maBC', '岡山'),
  ('quiNcMMg', 'リミナルスペース'),
  ('quiNcMMg', '廃校'),
  ('quiNcMMg', '廃墟'),
  ('quiNcMMg', '北海道'),
  ('prqyoo97', 'リミナルスペース'),
  ('prqyoo97', '廃校'),
  ('prqyoo97', '廃墟'),
  ('prqyoo97', '千葉'),
  ('tDPJKqS6', 'リミナルスペース'),
  ('tDPJKqS6', '廃校'),
  ('tDPJKqS6', '廃墟'),
  ('tDPJKqS6', '愛知'),
  ('QLwfbM4b', 'リミナルスペース'),
  ('QLwfbM4b', '廃校'),
  ('QLwfbM4b', '廃墟'),
  ('QLwfbM4b', '岐阜'),
  ('nHzr9PVP', 'リミナルスペース'),
  ('nHzr9PVP', '廃校'),
  ('nHzr9PVP', '廃墟'),
  ('nHzr9PVP', '北海道'),
  ('TmTsHg39', 'リミナルスペース'),
  ('TmTsHg39', '廃校'),
  ('TmTsHg39', '廃墟'),
  ('TmTsHg39', '愛知'),
  ('pW5UhxeC', 'リミナルスペース'),
  ('pW5UhxeC', '廃校'),
  ('pW5UhxeC', '廃墟'),
  ('pW5UhxeC', '北海道'),
  ('ep5tNFNY', 'リミナルスペース'),
  ('ep5tNFNY', '戦争遺構'),
  ('ep5tNFNY', '高知'),
  ('W69E6kQM', 'リミナルスペース'),
  ('W69E6kQM', 'スキー場跡'),
  ('W69E6kQM', '廃墟'),
  ('W69E6kQM', '北海道'),
  ('7KAQpruD', 'リミナルスペース'),
  ('7KAQpruD', '診療所跡'),
  ('7KAQpruD', '廃病院'),
  ('7KAQpruD', '廃墟'),
  ('7KAQpruD', '高知'),
  ('yG5KXJnB', 'リミナルスペース'),
  ('yG5KXJnB', '廃校'),
  ('yG5KXJnB', '廃墟'),
  ('yG5KXJnB', '岩手'),
  ('5aju7DnF', 'リミナルスペース'),
  ('5aju7DnF', '洋館'),
  ('5aju7DnF', '廃墟'),
  ('5aju7DnF', '宮城'),
  ('TekzRCTj', 'リミナルスペース'),
  ('TekzRCTj', '廃城'),
  ('TekzRCTj', '廃墟'),
  ('TekzRCTj', '高知'),
  ('adpu9uvm', 'リミナルスペース'),
  ('adpu9uvm', '廃ホテル'),
  ('adpu9uvm', '廃墟'),
  ('adpu9uvm', '愛知'),
  ('ZM9ZvdRe', 'リミナルスペース'),
  ('ZM9ZvdRe', '廃工場'),
  ('ZM9ZvdRe', '廃墟'),
  ('ZM9ZvdRe', '岡山'),
  ('Khnt6TG9', 'リミナルスペース'),
  ('Khnt6TG9', '廃発電所'),
  ('Khnt6TG9', '廃墟'),
  ('Khnt6TG9', '岩手'),
  ('qLkZzgjt', 'リミナルスペース'),
  ('qLkZzgjt', '廃発電所'),
  ('qLkZzgjt', '廃墟'),
  ('qLkZzgjt', '奈良'),
  ('ipqatQzY', 'リミナルスペース'),
  ('ipqatQzY', '廃発電所'),
  ('ipqatQzY', '廃墟'),
  ('ipqatQzY', '埼玉'),
  ('T86DUUf9', 'リミナルスペース'),
  ('T86DUUf9', '廃工場'),
  ('T86DUUf9', '廃墟'),
  ('T86DUUf9', '北海道'),
  ('Wqx5BmKq', 'リミナルスペース'),
  ('Wqx5BmKq', '廃工場'),
  ('Wqx5BmKq', '廃墟'),
  ('Wqx5BmKq', '青森'),
  ('A9wovu3T', 'リミナルスペース'),
  ('A9wovu3T', '廃工場'),
  ('A9wovu3T', '廃墟'),
  ('A9wovu3T', '秋田'),
  ('wmniXxM3', 'リミナルスペース'),
  ('wmniXxM3', '廃発電所'),
  ('wmniXxM3', '廃墟'),
  ('wmniXxM3', '愛知'),
  ('K4q9HiRe', 'リミナルスペース'),
  ('K4q9HiRe', '廃工場'),
  ('K4q9HiRe', '廃墟'),
  ('K4q9HiRe', '北海道'),
  ('XzQcU8bA', 'リミナルスペース'),
  ('XzQcU8bA', '廃工場'),
  ('XzQcU8bA', '廃墟'),
  ('XzQcU8bA', '岡山'),
  ('THCu2F55', 'リミナルスペース'),
  ('THCu2F55', '廃工場'),
  ('THCu2F55', '廃墟'),
  ('THCu2F55', '北海道'),
  ('U7zX35uL', 'リミナルスペース'),
  ('U7zX35uL', '廃工場'),
  ('U7zX35uL', '廃墟'),
  ('U7zX35uL', '愛知'),
  ('J2CGffXY', 'リミナルスペース'),
  ('J2CGffXY', '廃工場'),
  ('J2CGffXY', '廃墟'),
  ('J2CGffXY', '新潟'),
  ('DGSjLBzU', 'リミナルスペース'),
  ('DGSjLBzU', '廃工場'),
  ('DGSjLBzU', '廃墟'),
  ('DGSjLBzU', '新潟'),
  ('zWDz4tec', 'リミナルスペース'),
  ('zWDz4tec', '廃工場'),
  ('zWDz4tec', '廃墟'),
  ('zWDz4tec', '高知'),
  ('JzVmBYUD', 'リミナルスペース'),
  ('JzVmBYUD', '廃工場'),
  ('JzVmBYUD', '廃墟'),
  ('JzVmBYUD', '茨城'),
  ('Y9AGyNch', 'リミナルスペース'),
  ('Y9AGyNch', '廃工場'),
  ('Y9AGyNch', '廃墟'),
  ('Y9AGyNch', '茨城'),
  ('9iCXcXZo', 'リミナルスペース'),
  ('9iCXcXZo', '廃工場'),
  ('9iCXcXZo', '廃墟'),
  ('9iCXcXZo', '北海道'),
  ('EDs7a2go', 'リミナルスペース'),
  ('EDs7a2go', '廃工場'),
  ('EDs7a2go', '廃墟'),
  ('EDs7a2go', '山形'),
  ('cwDnEETU', 'リミナルスペース'),
  ('cwDnEETU', '廃工場'),
  ('cwDnEETU', '廃墟'),
  ('cwDnEETU', '茨城'),
  ('vQ4mzPej', 'リミナルスペース'),
  ('vQ4mzPej', '廃工場'),
  ('vQ4mzPej', '廃墟'),
  ('vQ4mzPej', '千葉'),
  ('oW44K9mN', 'リミナルスペース'),
  ('oW44K9mN', '廃工場'),
  ('oW44K9mN', '廃墟'),
  ('oW44K9mN', '神奈川'),
  ('oemoYTfG', 'リミナルスペース'),
  ('oemoYTfG', '廃発電所'),
  ('oemoYTfG', '廃墟'),
  ('oemoYTfG', '北海道'),
  ('3Yaocchj', 'リミナルスペース'),
  ('3Yaocchj', '廃工場'),
  ('3Yaocchj', '廃墟'),
  ('3Yaocchj', '栃木'),
  ('mmjcDRkP', 'リミナルスペース'),
  ('mmjcDRkP', '廃工場'),
  ('mmjcDRkP', '廃墟'),
  ('mmjcDRkP', '栃木'),
  ('eYYq3HTN', 'リミナルスペース'),
  ('eYYq3HTN', '廃工場'),
  ('eYYq3HTN', '廃墟'),
  ('eYYq3HTN', '茨城'),
  ('8fc35gjH', 'リミナルスペース'),
  ('8fc35gjH', '廃工場'),
  ('8fc35gjH', '廃墟'),
  ('8fc35gjH', '岐阜'),
  ('UpHfUMhu', 'リミナルスペース'),
  ('UpHfUMhu', '廃工場'),
  ('UpHfUMhu', '廃墟'),
  ('UpHfUMhu', '茨城'),
  ('Fj2N552g', 'リミナルスペース'),
  ('Fj2N552g', '廃工場'),
  ('Fj2N552g', '廃墟'),
  ('Fj2N552g', '茨城'),
  ('RSHeaFHg', 'リミナルスペース'),
  ('RSHeaFHg', '廃工場'),
  ('RSHeaFHg', '廃墟'),
  ('RSHeaFHg', '群馬'),
  ('CMzSqtkq', 'リミナルスペース'),
  ('CMzSqtkq', '廃工場'),
  ('CMzSqtkq', '廃墟'),
  ('CMzSqtkq', '茨城'),
  ('ALMwC5bG', 'リミナルスペース'),
  ('ALMwC5bG', '廃屋'),
  ('ALMwC5bG', '廃墟'),
  ('ALMwC5bG', '山梨'),
  ('otDUUTkK', 'バックルームズ'),
  ('otDUUTkK', '池袋'),
  ('otDUUTkK', '東京'),
  ('g5SSFruW', 'バックルームズ'),
  ('g5SSFruW', '赤坂'),
  ('g5SSFruW', '東京'),
  ('8QNryKdW', 'リミナルスペース'),
  ('8QNryKdW', '地下鉄駅'),
  ('8QNryKdW', '海外'),
  ('8QNryKdW', '駅'),
  ('8QNryKdW', '地下'),
  ('8QNryKdW', 'スウェーデン'),
  ('GGaTzjiy', 'リミナルスペース'),
  ('GGaTzjiy', '地下鉄駅'),
  ('GGaTzjiy', '海外'),
  ('GGaTzjiy', '駅'),
  ('GGaTzjiy', '地下'),
  ('GGaTzjiy', 'イタリア'),
  ('BZHyPP3o', 'リミナルスペース'),
  ('BZHyPP3o', '空港'),
  ('BZHyPP3o', '海外'),
  ('BZHyPP3o', '地下通路'),
  ('BZHyPP3o', '地下'),
  ('BZHyPP3o', 'アメリカ'),
  ('Lw7vXA3V', 'リミナルスペース'),
  ('Lw7vXA3V', '空港'),
  ('Lw7vXA3V', '海外'),
  ('Lw7vXA3V', 'フランス'),
  ('Lw7vXA3V', 'ブルータリズム'),
  ('sjnJteVJ', 'リミナルスペース'),
  ('sjnJteVJ', 'トンネル'),
  ('sjnJteVJ', '海外'),
  ('sjnJteVJ', '地下'),
  ('sjnJteVJ', 'ドイツ'),
  ('bDmapNGx', 'リミナルスペース'),
  ('bDmapNGx', '集合住宅'),
  ('bDmapNGx', '海外'),
  ('bDmapNGx', 'フランス'),
  ('UsmTFajm', 'リミナルスペース'),
  ('UsmTFajm', '駅'),
  ('UsmTFajm', '海外'),
  ('UsmTFajm', 'アメリカ'),
  ('2Vu5Nvv7', 'リミナルスペース'),
  ('2Vu5Nvv7', '空港'),
  ('2Vu5Nvv7', '海外'),
  ('2Vu5Nvv7', 'スペイン'),
  ('2USUpVzb', 'リミナルスペース'),
  ('2USUpVzb', '駅'),
  ('2USUpVzb', '海外'),
  ('2USUpVzb', 'ベルギー'),
  ('8uyxRJZG', 'リミナルスペース'),
  ('8uyxRJZG', '地下鉄駅'),
  ('8uyxRJZG', '海外'),
  ('8uyxRJZG', '駅'),
  ('8uyxRJZG', '地下'),
  ('8uyxRJZG', 'スウェーデン'),
  ('Cc7VvnrT', 'リミナルスペース'),
  ('Cc7VvnrT', '地下鉄駅'),
  ('Cc7VvnrT', '海外'),
  ('Cc7VvnrT', '駅'),
  ('Cc7VvnrT', '地下'),
  ('Cc7VvnrT', 'スウェーデン'),
  ('etS9YLnP', 'リミナルスペース'),
  ('etS9YLnP', '空港'),
  ('etS9YLnP', '海外'),
  ('etS9YLnP', 'アメリカ'),
  ('VVXMdSMV', 'リミナルスペース'),
  ('VVXMdSMV', '集合住宅'),
  ('VVXMdSMV', '海外'),
  ('VVXMdSMV', 'イギリス'),
  ('VVXMdSMV', 'ブルータリズム'),
  ('SxcZ69LR', 'リミナルスペース'),
  ('SxcZ69LR', '集合住宅'),
  ('SxcZ69LR', '海外'),
  ('SxcZ69LR', '南アフリカ'),
  ('x3hoBYtV', 'リミナルスペース'),
  ('x3hoBYtV', '地下鉄駅'),
  ('x3hoBYtV', '海外'),
  ('x3hoBYtV', '駅'),
  ('x3hoBYtV', '地下'),
  ('x3hoBYtV', 'ウクライナ'),
  ('pjaXkzcy', 'リミナルスペース'),
  ('pjaXkzcy', '計画都市'),
  ('pjaXkzcy', '海外'),
  ('pjaXkzcy', 'ゴーストタウン'),
  ('pjaXkzcy', '広場'),
  ('pjaXkzcy', '中国'),
  ('DvnXSY6X', 'リミナルスペース'),
  ('DvnXSY6X', '広場'),
  ('DvnXSY6X', '海外'),
  ('DvnXSY6X', 'アメリカ'),
  ('ahMnVhLD', 'リミナルスペース'),
  ('ahMnVhLD', '集合住宅'),
  ('ahMnVhLD', '海外'),
  ('ahMnVhLD', 'イギリス'),
  ('ahMnVhLD', 'ブルータリズム'),
  ('odS8ze5z', 'リミナルスペース'),
  ('odS8ze5z', '集合住宅'),
  ('odS8ze5z', '海外'),
  ('odS8ze5z', 'イタリア'),
  ('odS8ze5z', 'ブルータリズム'),
  ('Lmb9MUUi', 'リミナルスペース'),
  ('Lmb9MUUi', 'トンネル'),
  ('Lmb9MUUi', '海外'),
  ('Lmb9MUUi', 'ノルウェー'),
  ('UdwmdZmu', 'リミナルスペース'),
  ('UdwmdZmu', '集合住宅'),
  ('UdwmdZmu', '海外'),
  ('UdwmdZmu', 'セルビア'),
  ('UdwmdZmu', 'ブルータリズム'),
  ('auXGVFFE', 'リミナルスペース'),
  ('auXGVFFE', '公共施設'),
  ('auXGVFFE', '海外'),
  ('auXGVFFE', 'ルーマニア'),
  ('VE2WnRAp', 'リミナルスペース'),
  ('VE2WnRAp', 'バスターミナル'),
  ('VE2WnRAp', '海外'),
  ('VE2WnRAp', 'イギリス'),
  ('VE2WnRAp', 'ブルータリズム'),
  ('Db7cLF5y', 'リミナルスペース'),
  ('Db7cLF5y', '駅'),
  ('Db7cLF5y', '海外'),
  ('Db7cLF5y', 'ポルトガル'),
  ('EozrwoNy', 'リミナルスペース'),
  ('EozrwoNy', '地下鉄駅'),
  ('EozrwoNy', '海外'),
  ('EozrwoNy', '駅'),
  ('EozrwoNy', '地下'),
  ('EozrwoNy', '台湾'),
  ('sNq4kVMo', 'リミナルスペース'),
  ('sNq4kVMo', '地下鉄駅'),
  ('sNq4kVMo', '海外'),
  ('sNq4kVMo', '駅'),
  ('sNq4kVMo', '地下'),
  ('sNq4kVMo', 'ロシア'),
  ('HTpfFcWy', 'リミナルスペース'),
  ('HTpfFcWy', '広場'),
  ('HTpfFcWy', '海外'),
  ('HTpfFcWy', 'スペイン'),
  ('wS95uPD7', 'リミナルスペース'),
  ('wS95uPD7', '公共施設'),
  ('wS95uPD7', '海外'),
  ('wS95uPD7', 'メキシコ'),
  ('vH39Dc9M', 'リミナルスペース'),
  ('vH39Dc9M', '空港'),
  ('vH39Dc9M', '海外'),
  ('vH39Dc9M', '中国'),
  ('kEXNdF9Y', 'リミナルスペース'),
  ('kEXNdF9Y', '立体駐車場'),
  ('kEXNdF9Y', '海外'),
  ('kEXNdF9Y', '集合住宅'),
  ('kEXNdF9Y', 'アメリカ'),
  ('zEybC8RS', 'リミナルスペース'),
  ('zEybC8RS', '研究施設'),
  ('zEybC8RS', '海外'),
  ('zEybC8RS', 'ドイツ'),
  ('zEybC8RS', 'ブルータリズム'),
  ('F8ZXZ5kV', 'リミナルスペース'),
  ('F8ZXZ5kV', '集合住宅'),
  ('F8ZXZ5kV', '海外'),
  ('F8ZXZ5kV', 'イギリス'),
  ('F8ZXZ5kV', 'ブルータリズム'),
  ('z2qWaUEB', 'リミナルスペース'),
  ('z2qWaUEB', '団地'),
  ('z2qWaUEB', '海外'),
  ('z2qWaUEB', '集合住宅'),
  ('z2qWaUEB', '香港'),
  ('eZkorbK7', 'リミナルスペース'),
  ('eZkorbK7', '商業施設'),
  ('eZkorbK7', '海外'),
  ('eZkorbK7', '韓国'),
  ('rvEs5gKL', 'リミナルスペース'),
  ('rvEs5gKL', '駅'),
  ('rvEs5gKL', '海外'),
  ('rvEs5gKL', '地下鉄駅'),
  ('rvEs5gKL', '地下'),
  ('rvEs5gKL', 'ドイツ'),
  ('aMYSkmHZ', 'リミナルスペース'),
  ('aMYSkmHZ', '駅'),
  ('aMYSkmHZ', '海外'),
  ('aMYSkmHZ', '地下鉄駅'),
  ('aMYSkmHZ', '地下'),
  ('aMYSkmHZ', 'ウズベキスタン'),
  ('ETbKd2jH', 'リミナルスペース'),
  ('ETbKd2jH', 'ゴーストタウン'),
  ('ETbKd2jH', '海外'),
  ('ETbKd2jH', 'トルコ'),
  ('zsDBzZX3', 'リミナルスペース'),
  ('zsDBzZX3', 'サービスエリア'),
  ('zsDBzZX3', '海外'),
  ('zsDBzZX3', 'イギリス'),
  ('HhBNjW66', 'リミナルスペース'),
  ('HhBNjW66', '団地'),
  ('HhBNjW66', '海外'),
  ('HhBNjW66', '集合住宅'),
  ('HhBNjW66', 'イギリス'),
  ('HhBNjW66', 'ブルータリズム'),
  ('5uoQXuQ8', 'リミナルスペース'),
  ('5uoQXuQ8', '計画都市'),
  ('5uoQXuQ8', '海外'),
  ('5uoQXuQ8', 'カザフスタン'),
  ('JMeEx2vN', 'リミナルスペース'),
  ('JMeEx2vN', '団地'),
  ('JMeEx2vN', '海外'),
  ('JMeEx2vN', '集合住宅'),
  ('JMeEx2vN', 'オーストリア'),
  ('Rxz5y2My', 'リミナルスペース'),
  ('Rxz5y2My', '団地'),
  ('Rxz5y2My', '海外'),
  ('Rxz5y2My', '集合住宅'),
  ('Rxz5y2My', '香港'),
  ('bhAnQa6U', 'リミナルスペース'),
  ('bhAnQa6U', '駅'),
  ('bhAnQa6U', '海外'),
  ('bhAnQa6U', 'ベルギー'),
  ('jdR4Gh8o', 'リミナルスペース'),
  ('jdR4Gh8o', '集合住宅'),
  ('jdR4Gh8o', '海外'),
  ('jdR4Gh8o', 'アメリカ'),
  ('H3TU5VjM', 'リミナルスペース'),
  ('H3TU5VjM', '計画都市'),
  ('H3TU5VjM', '海外'),
  ('H3TU5VjM', 'イタリア'),
  ('nAxdFr63', 'リミナルスペース'),
  ('nAxdFr63', '集合住宅'),
  ('nAxdFr63', '海外'),
  ('nAxdFr63', 'カナダ'),
  ('nAxdFr63', 'ブルータリズム'),
  ('vAGShZq4', 'リミナルスペース'),
  ('vAGShZq4', '駅'),
  ('vAGShZq4', '海外'),
  ('vAGShZq4', '地下鉄駅'),
  ('vAGShZq4', '地下'),
  ('vAGShZq4', 'チェコ'),
  ('BYxVgBv8', 'リミナルスペース'),
  ('BYxVgBv8', '空港'),
  ('BYxVgBv8', '海外'),
  ('BYxVgBv8', 'スリランカ'),
  ('KewaKgjE', 'リミナルスペース'),
  ('KewaKgjE', '高架'),
  ('KewaKgjE', '海外'),
  ('KewaKgjE', 'ブラジル'),
  ('yZFZrRtZ', 'リミナルスペース'),
  ('yZFZrRtZ', '駅'),
  ('yZFZrRtZ', '海外'),
  ('yZFZrRtZ', 'イタリア'),
  ('QedBsTL4', 'リミナルスペース'),
  ('QedBsTL4', '駅'),
  ('QedBsTL4', '海外'),
  ('QedBsTL4', 'ドイツ'),
  ('Zi6c5ZgC', 'リミナルスペース'),
  ('Zi6c5ZgC', 'ゴーストタウン'),
  ('Zi6c5ZgC', '海外'),
  ('Zi6c5ZgC', 'アラブ首長国連邦'),
  ('NMmShzG7', 'リミナルスペース'),
  ('NMmShzG7', '廃墟'),
  ('NMmShzG7', '海外'),
  ('NMmShzG7', 'タイ'),
  ('TivYALh3', 'リミナルスペース'),
  ('TivYALh3', '廃墟'),
  ('TivYALh3', '海外'),
  ('TivYALh3', 'ブルガリア'),
  ('TivYALh3', 'ブルータリズム'),
  ('bqxwzKhM', 'リミナルスペース'),
  ('bqxwzKhM', '集合住宅'),
  ('bqxwzKhM', '海外'),
  ('bqxwzKhM', 'フランス'),
  ('bqxwzKhM', 'ブルータリズム'),
  ('ZoeUqjtb', 'リミナルスペース'),
  ('ZoeUqjtb', '駅'),
  ('ZoeUqjtb', '海外'),
  ('ZoeUqjtb', '地下鉄駅'),
  ('ZoeUqjtb', '地下'),
  ('ZoeUqjtb', 'フランス'),
  ('aRBAGXS8', 'リミナルスペース'),
  ('aRBAGXS8', '計画都市'),
  ('aRBAGXS8', '海外'),
  ('aRBAGXS8', 'ゴーストタウン'),
  ('aRBAGXS8', 'マレーシア'),
  ('XAyRF28R', 'リミナルスペース'),
  ('XAyRF28R', '集合住宅'),
  ('XAyRF28R', '海外'),
  ('XAyRF28R', 'スペイン'),
  ('cybiKBzm', 'リミナルスペース'),
  ('cybiKBzm', '計画都市'),
  ('cybiKBzm', '海外'),
  ('cybiKBzm', 'インド'),
  ('cybiKBzm', 'ブルータリズム'),
  ('aGkQCYCw', 'リミナルスペース'),
  ('aGkQCYCw', '集合住宅'),
  ('aGkQCYCw', '海外'),
  ('aGkQCYCw', 'スペイン'),
  ('qRzDQ5vp', 'リミナルスペース'),
  ('qRzDQ5vp', '計画都市'),
  ('qRzDQ5vp', '海外'),
  ('qRzDQ5vp', 'アンゴラ'),
  ('mAp7XKRg', 'リミナルスペース'),
  ('mAp7XKRg', 'ゴーストタウン'),
  ('mAp7XKRg', '海外'),
  ('mAp7XKRg', 'アメリカ'),
  ('qDakyLU3', 'リミナルスペース'),
  ('qDakyLU3', 'ゴーストタウン'),
  ('qDakyLU3', '海外'),
  ('qDakyLU3', 'ナミビア'),
  ('oERyKFTJ', 'リミナルスペース'),
  ('oERyKFTJ', '駅'),
  ('oERyKFTJ', '海外'),
  ('oERyKFTJ', '地下鉄駅'),
  ('oERyKFTJ', '地下'),
  ('oERyKFTJ', '北朝鮮'),
  ('5VJb3WDb', 'リミナルスペース'),
  ('5VJb3WDb', '廃墟'),
  ('5VJb3WDb', '海外'),
  ('5VJb3WDb', '北朝鮮'),
  ('EQ4XUbmu', 'リミナルスペース'),
  ('EQ4XUbmu', 'レジャー施設'),
  ('EQ4XUbmu', '海外'),
  ('EQ4XUbmu', 'プールコア'),
  ('EQ4XUbmu', 'ドイツ'),
  ('A74rJrvL', 'リミナルスペース'),
  ('A74rJrvL', '団地'),
  ('A74rJrvL', '海外'),
  ('A74rJrvL', '集合住宅'),
  ('A74rJrvL', '香港'),
  ('GLu6uDS2', 'リミナルスペース'),
  ('GLu6uDS2', 'ゴーストタウン'),
  ('GLu6uDS2', '海外'),
  ('GLu6uDS2', '炭鉱'),
  ('GLu6uDS2', 'ノルウェー'),
  ('3mPAPYhW', 'リミナルスペース'),
  ('3mPAPYhW', '廃線'),
  ('3mPAPYhW', '海外'),
  ('3mPAPYhW', '地下鉄駅'),
  ('3mPAPYhW', '地下'),
  ('3mPAPYhW', 'アメリカ'),
  ('srv9hfS7', 'リミナルスペース'),
  ('srv9hfS7', '廃線'),
  ('srv9hfS7', '海外'),
  ('srv9hfS7', '地下鉄駅'),
  ('srv9hfS7', '地下'),
  ('srv9hfS7', 'イギリス'),
  ('J9ANFBvC', 'リミナルスペース'),
  ('J9ANFBvC', '廃線'),
  ('J9ANFBvC', '海外'),
  ('J9ANFBvC', '地下鉄駅'),
  ('J9ANFBvC', '地下'),
  ('J9ANFBvC', 'アメリカ'),
  ('Dio8uQN2', 'リミナルスペース'),
  ('Dio8uQN2', '駅'),
  ('Dio8uQN2', '海外'),
  ('Dio8uQN2', 'イタリア'),
  ('UNSoSSWk', 'リミナルスペース'),
  ('UNSoSSWk', '計画都市'),
  ('UNSoSSWk', '海外'),
  ('UNSoSSWk', '中国'),
  ('GhMXEj8q', 'リミナルスペース'),
  ('GhMXEj8q', '廃墟'),
  ('GhMXEj8q', '海外'),
  ('GhMXEj8q', 'ポルトガル'),
  ('79p4o7ue', 'リミナルスペース'),
  ('79p4o7ue', '廃墟'),
  ('79p4o7ue', '海外'),
  ('79p4o7ue', 'ボスニア・ヘルツェゴビナ'),
  ('55S5FZeL', 'リミナルスペース'),
  ('55S5FZeL', '地下'),
  ('55S5FZeL', '海外'),
  ('55S5FZeL', 'オーストラリア'),
  ('Mvs56E7i', 'リミナルスペース'),
  ('Mvs56E7i', 'ゴーストタウン'),
  ('Mvs56E7i', '海外'),
  ('Mvs56E7i', '水没'),
  ('Mvs56E7i', 'アルゼンチン'),
  ('9aLUxoT8', 'リミナルスペース'),
  ('9aLUxoT8', 'ゴーストタウン'),
  ('9aLUxoT8', '海外'),
  ('9aLUxoT8', '産業遺産'),
  ('9aLUxoT8', '世界遺産'),
  ('9aLUxoT8', 'チリ'),
  ('rTGPj4y9', 'リミナルスペース'),
  ('rTGPj4y9', '地下街'),
  ('rTGPj4y9', '海外'),
  ('rTGPj4y9', '地下'),
  ('rTGPj4y9', '駅'),
  ('rTGPj4y9', 'カナダ'),
  ('7XgJ2pw4', 'リミナルスペース'),
  ('7XgJ2pw4', '計画都市'),
  ('7XgJ2pw4', '海外'),
  ('7XgJ2pw4', 'トルクメニスタン'),
  ('84YSwrm3', 'リミナルスペース'),
  ('84YSwrm3', '公共施設'),
  ('84YSwrm3', '海外'),
  ('84YSwrm3', 'アゼルバイジャン'),
  ('sDGqDpaA', 'リミナルスペース'),
  ('sDGqDpaA', 'ゴーストタウン'),
  ('sDGqDpaA', '海外'),
  ('sDGqDpaA', 'イタリア'),
  ('RpUyExpq', 'リミナルスペース'),
  ('RpUyExpq', 'ゴーストタウン'),
  ('RpUyExpq', '海外'),
  ('RpUyExpq', 'トルコ'),
  ('gEpPMKQ6', 'リミナルスペース'),
  ('gEpPMKQ6', '計画都市'),
  ('gEpPMKQ6', '海外'),
  ('gEpPMKQ6', 'エジプト'),
  ('o7nfsxtg', 'リミナルスペース'),
  ('o7nfsxtg', '集合住宅'),
  ('o7nfsxtg', '海外'),
  ('o7nfsxtg', 'セルビア'),
  ('o7nfsxtg', 'ブルータリズム'),
  ('fFLMGMbg', 'リミナルスペース'),
  ('fFLMGMbg', '駅'),
  ('fFLMGMbg', '海外'),
  ('fFLMGMbg', '地下鉄駅'),
  ('fFLMGMbg', '地下'),
  ('fFLMGMbg', 'イギリス'),
  ('ib3BSyoC', 'リミナルスペース'),
  ('ib3BSyoC', '公共施設'),
  ('ib3BSyoC', '海外'),
  ('ib3BSyoC', '北マケドニア'),
  ('ib3BSyoC', 'ブルータリズム'),
  ('5c4qXbrK', 'リミナルスペース'),
  ('5c4qXbrK', '駅'),
  ('5c4qXbrK', '海外'),
  ('5c4qXbrK', '地下鉄駅'),
  ('5c4qXbrK', '地下'),
  ('5c4qXbrK', 'スウェーデン'),
  ('qptwvrZR', 'リミナルスペース'),
  ('qptwvrZR', 'レジャー施設'),
  ('qptwvrZR', '海外'),
  ('qptwvrZR', '廃遊園地'),
  ('qptwvrZR', '廃墟'),
  ('qptwvrZR', 'ベトナム'),
  ('QAKdeuaZ', 'リミナルスペース'),
  ('QAKdeuaZ', 'ゴーストタウン'),
  ('QAKdeuaZ', '海外'),
  ('QAKdeuaZ', 'イタリア'),
  ('9dLFK2qh', 'リミナルスペース'),
  ('9dLFK2qh', '公共施設'),
  ('9dLFK2qh', '海外'),
  ('9dLFK2qh', 'ブラジル'),
  ('UeKBsfTf', 'リミナルスペース'),
  ('UeKBsfTf', '廃線'),
  ('UeKBsfTf', '海外'),
  ('UeKBsfTf', '駅'),
  ('UeKBsfTf', '廃墟'),
  ('UeKBsfTf', 'アメリカ'),
  ('JNp6eaQC', 'リミナルスペース'),
  ('JNp6eaQC', '公共施設'),
  ('JNp6eaQC', '海外'),
  ('JNp6eaQC', 'コートジボワール'),
  ('2yNy9E97', 'リミナルスペース'),
  ('2yNy9E97', '駅'),
  ('2yNy9E97', '海外'),
  ('2yNy9E97', '地下鉄駅'),
  ('2yNy9E97', '地下'),
  ('2yNy9E97', 'ロシア'),
  ('eJ7VP53r', 'リミナルスペース'),
  ('eJ7VP53r', '団地'),
  ('eJ7VP53r', '海外'),
  ('eJ7VP53r', '集合住宅'),
  ('eJ7VP53r', '香港'),
  ('5g7LAi9Y', 'リミナルスペース'),
  ('5g7LAi9Y', '計画都市'),
  ('5g7LAi9Y', '海外'),
  ('5g7LAi9Y', 'ブラジル'),
  ('65CEvUYF', 'リミナルスペース'),
  ('65CEvUYF', '広場'),
  ('65CEvUYF', '海外'),
  ('65CEvUYF', 'アメリカ'),
  ('65CEvUYF', 'ブルータリズム'),
  ('UUa8yY66', 'リミナルスペース'),
  ('UUa8yY66', '屋内プール'),
  ('UUa8yY66', '海外'),
  ('UUa8yY66', 'プールコア'),
  ('UUa8yY66', '温泉'),
  ('UUa8yY66', 'スイス'),
  ('xjHULppd', 'リミナルスペース'),
  ('xjHULppd', '公共施設'),
  ('xjHULppd', '海外'),
  ('xjHULppd', '韓国'),
  ('SdUSWAUL', 'リミナルスペース'),
  ('SdUSWAUL', '駅'),
  ('SdUSWAUL', '海外'),
  ('SdUSWAUL', 'オランダ')
) as v(slug, tag)
join public.spots s on s.slug = v.slug
join public.tags t on t.name = v.tag
where s.author_id = (select id from public.profiles where username = 'LIMap')
on conflict do nothing;

-- 6. 使われていない誤字タグの削除
delete from public.tags t
where t.name in ('廃墨', '青専ビル街')
  and not exists (select 1 from public.spot_tags st where st.tag_id = t.id);

commit;

-- 確認用（実行後に流す）:
-- select count(*) from public.spots where slug in ('gVpMv3sF', 'Durek4me', '8P62RQ4b', ...);  -- 0 になる
-- select t.name, count(*) from public.spot_tags st join public.tags t on t.id = st.tag_id group by t.name order by 2 desc;
